---
- name: jenkins ansible deployment
  hosts: all
  become: true

  task:
    - name: docker container run
      docker_container:
        name: web
        image: nginx:latest
        tty: true
        state: started
        ports:
          -  "80:80"
